name: Node.js CI

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    env:
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js v20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Run Tests
        uses: willcaul/jest-github-action@v4
        with: 
          GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
